# Generated by Django 2.2.16 on 2022-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20220613_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoroffer',
            name='type',
            field=models.CharField(choices=[
                ('Offer', 'Offer'),
                ('Category', 'Category')],
                default='Category',
                max_length=50,
                verbose_name='Type'),
            preserve_default=False,
        ),
    ]
