# Generated by Django 2.2.16 on 2022-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_categoryoroffer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoroffer',
            name='type',
            field=models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=50, verbose_name='Type'),
        ),
    ]
