# Generated by Django 2.2.16 on 2022-06-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_auto_20220613_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoroffer',
            name='parent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children', to='imports.CategoryOrOffer'),
        ),
    ]
