# Generated by Django 2.2.16 on 2022-06-22 11:01

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0007_auto_20220617_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCategoryOrOffer',
            fields=[
                ('id', models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date', models.DateTimeField(verbose_name='Update date')),
                ('price', models.IntegerField(
                    null=True, verbose_name='Price')),
                ('type', models.CharField(choices=[
                    ('OFFER', 'Offer'),
                    ('CATEGORY', 'Category')],
                    max_length=50,
                    verbose_name='Type')),
                ('history_id', models.AutoField(
                    primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(
                    max_length=100, null=True)),
                ('history_type', models.CharField(choices=[
                    ('+', 'Created'),
                    ('~', 'Changed'),
                    ('-', 'Deleted')],
                    max_length=1)),
                ('history_user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+', to='imports.CategoryOrOffer')),
            ],
            options={
                'verbose_name': 'historical Entity',
                'verbose_name_plural': 'historical Entities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
