# Generated by Django 2.2.16 on 2022-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_historicalcategoryoroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoroffer',
            name='avg_price',
            field=models.IntegerField(null=True, verbose_name='Average price'),
        ),
        migrations.AddField(
            model_name='historicalcategoryoroffer',
            name='avg_price',
            field=models.IntegerField(null=True, verbose_name='Average price'),
        ),
    ]
